controllers/ArticleController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Article;
use app\models\ArticleSearch;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						// 'actions' => ['index', 'view', 'slug', 'create', 'update', 'delete'],
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, ['pagination' => [ 'pageSize' => 10 ]]);

		$dataProvider = new ActiveDataProvider([
			'query' => Article::find()->where(['authorId' => Yii::$app->user->identity->getId()]),
			'pagination' => [
				'pageSize' => 1,
			],
		]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModelById($id),
        ]);
    }

	/**
	 * Displays a single Article model.
	 * @param string $slug
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionSlug($slug)
	{
		return $this->render('view', [
			'model' => $this->findModelBySlug($slug),
		]);
	}

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();

        $model->authorId = Yii::$app->user->identity->getId();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['slug', 'slug' => $model->slug]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModelById($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['slug', 'slug' => $model->slug]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModelById($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelById($id)
    {
		return $this->findModel(['id' => $id]);
    }

	/**
	 * Finds the Article model based on its slug value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param string $slug
	 * @return Article the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModelBySlug($slug)
	{
		return $this->findModel(['slug' => $slug]);
	}

	/**
	 * Finds the Article model based on passed condition.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param array $condition
	 * @return Article the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($condition)
	{
		$condition['authorId'] = Yii::$app->user->id;
		if (($model = Article::findOne($condition)) !== null) {
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}
}

controllers/AuthController.php
<?php

namespace app\controllers;

use app\components\AuthHandler;
use app\models\ChangePasswordForm;
use app\models\PasswordForm;
use app\models\RegistrationForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\base\Exception;
use yii\web\Controller;
use yii\web\Response;
use app\models\LoginForm;

class AuthController extends Controller
{
	public $layout = 'auth';

	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'auth' => [
				'class' => 'yii\authclient\AuthAction',
				'successCallback' => [$this, 'onAuthSuccess'],
			],
		];
	}

	/**
	 * Handles login via third-party services.
	 *
	 * @param $client
	 */
	public function onAuthSuccess($client)
	{
		(new AuthHandler($client))->handle();
	}

	/**
	 * Register action.
	 *
	 * @return Response|string
	 * @throws Exception
	 */
	public function actionRegister()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new RegistrationForm();
		if ($model->load(Yii::$app->request->post()) && $model->register()) {
			Yii::$app->getSession()->setFlash('success', Yii::t('app',Html::encode('You\'ve been successfully registered! Now you can login!')));
			$this->redirect(['auth/login']);
		}

		$model->password = '';
		$model->passwordRepeat = '';
		return $this->render('register', [
			'model' => $model,
		]);
	}

	/**
 * Login action.
 *
 * @return Response|string
 */
	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		}

		$model->password = '';
		return $this->render('login', [
			'model' => $model,
		]);
	}

	/**
	 * Forgot password action.
	 *
	 * @return string|Response
	 * @throws Exception
	 */
	public function actionPassword()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new PasswordForm();
		if ($model->load(Yii::$app->request->post()) && $model->resetPassword()) {
			Yii::$app->getSession()->setFlash('success', 'Check your inbox <strong>' . $model->username . '</strong>. There will be password reset link.');
		}

		return $this->render('password', [
			'model' => $model,
		]);
	}

	/**
	 * Forgot action.
	 *
	 * @param $token string
	 * @return Response|string
	 */
	public function actionChangePassword($token)
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$user = User::findByPasswordResetToken($token);

		$model = new ChangePasswordForm();
		$model->username = $user->email;
		if ($model->load(Yii::$app->request->post()) && $model->changePassword()) {
			Yii::$app->getSession()->setFlash('success', Yii::t('app',Html::encode('Your password has been successfully changed! You can now login with your new password!')));
			$this->redirect(['auth/login']);
		}

		// If user goes to link and change password after minute or later, let him do that
		if(!$user->canChangePassword()) {
			Yii::$app->getSession()->setFlash('failure', Yii::t('app',Html::encode('Password change token expired!')));
			$this->redirect(['auth/password']);
		}

		return $this->render('change-password', [
			'model' => $model,
		]);
	}

	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

}

views/layouts/auth.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php $this->registerCsrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="auth">
    <div class="wrap">
        <div class="container">
            <?= $content ?>
        </div>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
	<?php
	if (!Yii::$app->user->isGuest) {
		NavBar::begin([
			'brandLabel' => Html::img('@web/images/logo.png', ['style' => 'max-width:100px; margin-top: -4px;', 'alt' => Yii::$app->name]),
			'brandUrl' => Yii::$app->homeUrl,
			'options' => [
				'class' => 'navbar-inverse navbar-fixed-top',
			],
		]);

		echo Nav::widget([
			'options' => ['class' => 'navbar-nav navbar-right'],
			'items' => [
				['label' => 'Home', 'url' => ['/article/index']],
				(
					'<li>'
					. Html::beginForm(['/auth/logout'], 'post')
					. Html::submitButton(
						'Sign out',
						['class' => 'btn btn-link logout']
					)
					. Html::endForm()
					. '</li>'
				),
                (
                    '<li>'
                    . '<p class="navbar-text navbar-right">'
					. '<span class="glyphicon glyphicon-user"></span> '
                    . Yii::$app->user->identity->fullName
                    . '</p>'
                    . '</li>'
                )
			],
		]);

		NavBar::end();
	}
	?>

    <div class="container">
		<?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>